spring:
  profiles:
    active:
      - standalone
  application:
    name: flex
  messages:
    basename: i18n/messages
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://root:password@localhost:27017/?authSource=admin}
      database: ${MONGO_DATABASE:flex}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:user}
    password: ${RABBITMQ_PASSWORD:password}

logging:
  level:
    root: INFO
    es.brasatech: DEBUG
    org.springframework: INFO