# Java CI/CD with Maven DockerHub Google Artifact Registry and Google Cloud Run
name: Java CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  CLOUD_RUN_SERVICE: ${{ secrets.CLOUD_RUN_SERVICE_NAME }}
  ARTIFACT_REGISTRY_REPO: ${{ secrets.ARTIFACT_REGISTRY_REPO }}
  IMAGE_NAME: flex-non-native
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        cache: maven
    - name: Build with Maven
      run: mvn package

    - name: Build the Docker image
      run: docker build . --file Dockerfile-NonNative --tag ricardomaximino/flex-non-native:latest  --build-arg NAME=target/flex-0.0.1-SNAPSHOT.jar

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push image to Docker Hub
      run: docker push ricardomaximino/flex-non-native:latest

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Configure Docker to use Google Artifact Registry
      run: gcloud auth configure-docker ${REGION}-docker.pkg.dev

    - name: Tag and Push Docker Image to Google Artifact Registry
      run: |
        # The full image name for Artifact Registry
        FULL_GCR_IMAGE=${REGION}-docker.pkg.dev/${PROJECT_ID}/${ARTIFACT_REGISTRY_REPO}/${IMAGE_NAME}:${{ github.sha }}
        docker tag ricardomaximino/flex-non-native:latest $FULL_GCR_IMAGE
        docker push $FULL_GCR_IMAGE
        
        # Make the full image name available for the next step
        echo "FULL_GCR_IMAGE=$FULL_GCR_IMAGE" >> $GITHUB_ENV

    - name: Deploy to Google Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.CLOUD_RUN_SERVICE }}
        region: ${{ env.REGION }}
        image: ${{ env.FULL_GCR_IMAGE }}
